language: python

python:
  - '3.8'

env:
  global:
    - secure: GMUWLBrNBeYmVLr+KBXnFhKGb3RLrY6qgApQ9JgMiNBTlmcgVq5tpUYSpQpQTHXVmnU0Xho/NpWo27+ud2QJqXEtgp9q/ZGxrEJsX3SAtUBONphMSjEbaHiH90MgMmgS2wtyxuptKoL66vJ3SLtbTgcMWmEvyMbN0n+f/qIRtlk=

install:
  - python setup.py install

script:
  - python setup.py nosetests # Run all tests
#  - python setup.py nosetests --where=tests/unit # Run unit tests
#  - python setup.py nosetests --where=tests/integration # Run integration tests

after_success:
        - coveralls #--data_file coverage.xml
